/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import supermecado.Almacen;
import supermecado.Empleado;
import supermecado.ObjectNotFoundException;

/**
 *
 * @author atenea
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private Almacen tienda = null;
    private Ventana venta = null;
    private VentasRealizadas realizadas = null;

    public Principal(Almacen almacen) {
        this.tienda = almacen;
        initComponents();
        super.addWindowListener(new WindowListener() {

            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                ObjectOutputStream os =null;
                try {
                     os = new ObjectOutputStream(new FileOutputStream("prueba.data"));
                    os.writeObject(Principal.this.tienda);
                } catch (IOException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }finally{
                    if (os != null){
                        try {
                            os.close();
                        } catch (IOException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                
            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
        
        ManejadorVentana mv = new ManejadorVentana();
        mostrarVenta.addActionListener(mv);

        ManejadorVentasRealizadas mvr = new ManejadorVentasRealizadas();
        mostrarV.addActionListener(mvr);

        loginEmpleado le = new loginEmpleado();
        contraseña.addActionListener(le);
        aceptar.addActionListener(le);

        CerrarSesion mcs = new CerrarSesion();
        cerrar.addActionListener(mcs);

//        FORMA  ANONIMA
//        mostrarVenta.addActionListener(new ActionListener() {
//
//            @Override
//            public void actionPerformed(ActionEvent e) {
//               if(venta==null){
//                   venta = new Ventana(tienda);
//                   Escritorio.add(venta);
//               }
//               venta.setVisible(true);
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        login = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mostrarVenta = new javax.swing.JMenuItem();
        mostrarV = new javax.swing.JMenuItem();
        cerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(new java.awt.Color(6, 129, 221));

        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Usuario");

        jLabel6.setText("Contraseña");

        aceptar.setText("Aceptar");

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(contraseña))
                .addGap(96, 96, 96))
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptar)
                .addContainerGap())
        );

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
            .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EscritorioLayout.createSequentialGroup()
                    .addGap(291, 291, 291)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(291, Short.MAX_VALUE)))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
            .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EscritorioLayout.createSequentialGroup()
                    .addGap(190, 190, 190)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(214, Short.MAX_VALUE)))
        );
        Escritorio.setLayer(login, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("File");

        mostrarVenta.setText("Realizar venta");
        mostrarVenta.setEnabled(false);
        jMenu1.add(mostrarVenta);

        mostrarV.setText("ventas realizadas");
        mostrarV.setEnabled(false);
        jMenu1.add(mostrarV);

        cerrar.setText("cerrar  sesión");
        cerrar.setEnabled(false);
        jMenu1.add(cerrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Escritorio)
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JButton aceptar;
    private javax.swing.JMenuItem cerrar;
    private javax.swing.JTextField contraseña;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel login;
    private javax.swing.JMenuItem mostrarV;
    private javax.swing.JMenuItem mostrarVenta;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

    public class ManejadorVentana implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (venta == null) {
                venta = new Ventana(tienda);
                Escritorio.add(venta);
            }
            venta.setVisible(true);
        }

    }

    public class ManejadorVentasRealizadas implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (realizadas == null) {
                realizadas = new VentasRealizadas(tienda);
                Escritorio.add(realizadas);
            }
            realizadas.setVisible(true);
        }

    }

    public class loginEmpleado implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            try {
                Empleado empleado = tienda.BuscarEmpleado(usuario.getText().trim());
                if (empleado.getPassword().equals(contraseña.getText().trim())) {
                    tienda.logueado = empleado;
                    mostrarVenta.setEnabled(true);
                    mostrarV.setEnabled(true);
                    cerrar.setEnabled(true);
                    login.setVisible(false);
                   //ManejadorVentana mv = new ManejadorVentana();
                    // mv.actionPerformed(e);
                    new ManejadorVentana().actionPerformed(e);
                } else {
                    JOptionPane.showMessageDialog(null, "La contraseña no es correcta");
                }

            } catch (ObjectNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        }

    }

    public class CerrarSesion implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            mostrarVenta.setEnabled(false);
            mostrarV.setEnabled(false);
            cerrar.setEnabled(false);
            login.setVisible(true);
            venta.setVisible(false);
            realizadas.setVisible(false);
            venta.cv.actionPerformed(e); // para cancelar la venta cuando se cierra la sesion

        }

    }

}
