/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.AbstractTableModel;
import supermecado.Almacen;
import supermecado.Compra;
import supermecado.DetalleCompra;

/**
 *
 * @author atenea
 */
public class VentasRealizadas extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    private Almacen tienda = null;

    public VentasRealizadas(Almacen almacen) {
        initComponents();
        this.tienda = almacen;

        this.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                super.internalFrameActivated(e);
                tablaVentas.updateUI();

            }

        });

        this.tablaVentas.setModel(new AbstractTableModel() {

            @Override
            public int getRowCount() {
                if (tienda == null) {
                    return 0;
                }
                return tienda.getCompras().size();
            }

            @Override
            public int getColumnCount() {
                return 4;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Vendedor";
                    case 1:
                        return "Cliente";
                    case 2:
                        return "Costo";
                    case 3:
                        return "Puntos otorgados";
                }
                return "";
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Compra compra = tienda.getCompras().get(rowIndex);
                switch (columnIndex) {
                    case 0:
                        return compra.getEmpleado().getNombres() + " " + compra.getEmpleado().getApellidos();
                    case 1:
                        return compra.getCliente().getNombres() + " " + compra.getEmpleado().getApellidos();
                    case 2:
                        return compra.getCostoTotal();
                    case 3:
                        return compra.puntosCompra();
                }
                return "";
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}
